"""Add_complexity_levels_for_tasks

Revision ID: b3586c3030c9
Revises: 27c8315a7dd8
Create Date: 2023-02-07 10:14:26.002966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3586c3030c9'
down_revision = '27c8315a7dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treeitemmetadata', sa.Column('management', sa.Integer(), nullable=True))
    op.add_column('treeitemmetadata', sa.Column('development', sa.Integer(), nullable=True))
    op.add_column('treeitemmetadata', sa.Column('exploitation', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treeitemmetadata', 'exploitation')
    op.drop_column('treeitemmetadata', 'development')
    op.drop_column('treeitemmetadata', 'management')
    # ### end Alembic commands ###
