"""Add_complexity_levels_for_tasks_defaults

Revision ID: b4a2cee711de
Revises: b3586c3030c9
Create Date: 2023-02-07 10:46:08.455669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a2cee711de'
down_revision = 'b3586c3030c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('treeitemmetadata', 'management',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('treeitemmetadata', 'development',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('treeitemmetadata', 'exploitation',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('treeitemmetadata', 'exploitation',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('treeitemmetadata', 'development',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('treeitemmetadata', 'management',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
