name: build-and-publish-docker

on:

  workflow_dispatch:

  push:
    tags:
      - '*'

    branches:
      - master
      - seed_data

jobs:
  # Do not create image before merging the seed data (on-seed-data-changes workflow triggers this workflow when finished)
  conditional_job_check_files:
    runs-on: ubuntu-latest
    outputs:
      seed_data_changed: ${{ steps.check_file_changed.outputs.seed_data_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - shell: pwsh
        id: check_file_changed
        run: |
          # Diff HEAD with the previous commit
          $diff = git diff --name-only HEAD^ HEAD

          # Check if a file under catalogue/seed/ or with the .md extension has changed (added, modified, deleted)
          $SourceDiff = $diff | Where-Object { $_ -match '^catalogue/seed/' -or $_ -match '.md$' }
          $HasDiff = $SourceDiff.Length -gt 0

          # Set the output named "seed_data_changed"
          Write-Host "::set-output name=seed_data_changed::$HasDiff"

  # if seed data not changed, run the job and create the docker image
  docker:
    runs-on: ubuntu-latest
    needs: [ conditional_job_check_files ]
    if: needs.conditional_job_check_files.outputs.seed_data_changed == 'False'
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            interlinkproject/backend-catalogue:${{ github.ref_name }}
            interlinkproject/backend-catalogue:${{ github.ref_name }}.${{ steps.date.outputs.date }}
          cache-from: type=registry,ref=interlinkproject/backend-catalogue:buildcache
          cache-to: type=registry,ref=interlinkproject/backend-catalogue:buildcache,mode=max

      - name: Trigger Dev Deployment
        uses: octokit/request-action@v2.x
        id: trigger_dev_deployment
        with:
          route: POST /repos/{owner}/{repo}/dispatches
          owner: interlink-project
          repo: interlink-project
          event_type: update-dev-environment
        env:
          GITHUB_TOKEN: ${{ secrets.INTERLINK_PROJECT_GITHUB_TOKEN }}
