name: Check if seed files have changed

on:

  workflow_dispatch:

  push:
    tags:
      - '*'
    branches:
      - master
      - seed_data

jobs:
  # If seed data changed, test it before creating the docker image
  check_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v10
        id: verify-changed-files
        with:
          files: |
            catalogue/seed/**

      - name: Trigger Docker image recreation
        uses: octokit/request-action@v2.x
        id: trigger_docker_image_recreation
        if: steps.verify-changed-files.outputs.files_changed == 'false'
        with:
          route: POST /repos/{owner}/{repo}/dispatches
          owner: interlink-project
          repo: backend-catalogue
          event_type: build-and-publish-docker
        env:
          GITHUB_TOKEN: ${{ secrets.INTERLINK_PROJECT_GITHUB_TOKEN }}
      
      - name: Trigger Docker image recreation
        uses: octokit/request-action@v2.x
        id: trigger_seed_data_tests
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        with:
          route: POST /repos/{owner}/{repo}/dispatches
          owner: interlink-project
          repo: backend-catalogue
          event_type: test-seed-data-changes
        env:
          GITHUB_TOKEN: ${{ secrets.INTERLINK_PROJECT_GITHUB_TOKEN }}